# Generated by Django 5.2.17 on 2026-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
