# Generated by Django 5.2.17 on 2026-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_slug',
            field=models.CharField(blank=True, default='', help_text='Slug ikon dari devicon.dev, contoh: python/python-original', max_length=100),
        ),
    ]
